name: bufalabuona
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^1.6.3
  sqflite: ^2.2.6
  path_provider: ^2.0.14
  email_validator: ^2.0.1
  flutter_dotenv: ^5.0.2
  url_strategy: ^0.2.0
  url_launcher: ^6.1.6
  flutter_web_auth: ^0.4.0
  flutter_secure_storage: ^4.2.0
  image_picker: ^0.8.2
  rounded_loading_button: ^2.0.5  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  json_annotation: ^4.7.0
  dio: ^4.0.6
  font_awesome_flutter: ^10.3.0
  package_info_plus: ^3.0.2
  equatable: ^2.0.5
  flex_seed_scheme: ^1.1.0
  rotated_corner_decoration: ^2.1.0+1
  fluttertoast: ^8.1.2
  connectivity_plus: ^2.3.0
  intl: ^0.18.0
  persistent_bottom_nav_bar: ^5.0.2
  add_to_cart_animation: ^2.0.0
  badges: ^2.0.3
  shared_preferences: ^2.0.15
  firebase_core: ^2.2.0
  firebase_crashlytics: ^3.0.5
  firebase_messaging: ^14.1.0
  firebase_remote_config: ^3.0.5
  permission_handler: ^10.2.0
  device_info_plus: ^6.0.0
  platform_device_id: ^1.0.1
#  proviamo a identificare il singolo device recuperando il mac address, visto che non funziona più su android get AndroidId.
#  get_mac: ^0.0.1
  overlay_support: ^2.1.0
  uni_links: ^0.5.1
  flutter_ringtone_player: ^3.2.0
  video_player: ^2.5.1
  cached_network_image: 3.2.3
  flutter_blurhash: ^0.7.0
  flutter_riverpod: ^2.3.4

  # create pdf document
#  pdf: ^3.1.0
  pdf: ^3.10.1


  # open pdf document
#  open_file: ^3.1.0
  open_filex: ^4.1.1
  google_fonts: ^4.0.4


dev_dependencies:

  build_runner: ^2.2.0
  json_serializable: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  change_app_package_name: ^1.0.0



flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon_logo.png"
  min_sdk_android: 21


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/images/
    - assets/animated/
    - assets/sounds/
    - assets/videos/
    - assets/fonts/
