// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy9koGQ4-Oxq5oiaZyLBN3bHgJDNi0_Z4',
    appId: '1:675275977106:web:64cb27a4a7f42fcc3b514b',
    messagingSenderId: '675275977106',
    projectId: 'mozzarella-connection-a8589',
    authDomain: 'mozzarella-connection-a8589.firebaseapp.com',
    storageBucket: 'mozzarella-connection-a8589.appspot.com',
    measurementId: 'G-M99EMQ5ZFC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi-NSgPzN4W0a6bDuProGQ5Zw67T07k3M',
    appId: '1:675275977106:android:3f5c8f0392f4343a3b514b',
    messagingSenderId: '675275977106',
    projectId: 'mozzarella-connection-a8589',
    storageBucket: 'mozzarella-connection-a8589.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWBEWcHjbjrbbv1VcJ_McLoK21rp3-G_I',
    appId: '1:675275977106:ios:bae84797808141fa3b514b',
    messagingSenderId: '675275977106',
    projectId: 'mozzarella-connection-a8589',
    storageBucket: 'mozzarella-connection-a8589.appspot.com',
    iosClientId: '675275977106-0fhnl9lr00rhjh266kjlnm3nb7f2n2kb.apps.googleusercontent.com',
    iosBundleId: 'com.aziendaagricoladangelo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWBEWcHjbjrbbv1VcJ_McLoK21rp3-G_I',
    appId: '1:675275977106:ios:bae84797808141fa3b514b',
    messagingSenderId: '675275977106',
    projectId: 'mozzarella-connection-a8589',
    storageBucket: 'mozzarella-connection-a8589.appspot.com',
    iosClientId: '675275977106-0fhnl9lr00rhjh266kjlnm3nb7f2n2kb.apps.googleusercontent.com',
    iosBundleId: 'com.aziendaagricoladangelo',
  );
}
