// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPzakO2UtdgngDSetnYBJahuhA1gXCj54',
    appId: '1:70115041987:web:4dc1c85fc0f664f3cfb876',
    messagingSenderId: '70115041987',
    projectId: 'bufalabuona',
    authDomain: 'bufalabuona.firebaseapp.com',
    storageBucket: 'bufalabuona.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwecfsudZre_nlOkgNpZFyW_UvrW4GazM',
    appId: '1:70115041987:android:d21683325db8a9d1cfb876',
    messagingSenderId: '70115041987',
    projectId: 'bufalabuona',
    storageBucket: 'bufalabuona.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZKvfOXXEajupDGreagCZYOO3YvFiXzjo',
    appId: '1:70115041987:ios:c4d196ea07557050cfb876',
    messagingSenderId: '70115041987',
    projectId: 'bufalabuona',
    storageBucket: 'bufalabuona.appspot.com',
    iosClientId: '70115041987-i243m8oclodkqiucqq3jsld57ke5fihm.apps.googleusercontent.com',
    iosBundleId: 'com.aziendaagricoladangelo',
  );
}
